url: https://charley-danica.github.io
#baseurl: /wedding-template

# Site settings
title: Charley&Danica
description: "Charley and Danica are getting married"


# Build settings
markdown: kramdown
permalink: pretty

include: ['_en_pages', '_sr_pages', '_zh_pages']