url: https://charley-danica.github.io
#baseurl: /wedding-template

# Site settings
title: Charley and Danica
email: petsgetmarried@wedding.com
description: "Template for a wedding website."


# Build settings
markdown: kramdown
permalink: pretty

include: ['_en_pages', '_sr_pages', '_zh_pages']